project:
  type: website
  output-dir: docs

website:
  description: "O giełdzie i danych w przystępny sposób"
  site-url: https://tszczerbicki.github.io/quarto-site/
  title: "Tomasz Szczerbicki - analizy giełdowe"
  favicon: "favicon_cropped.png"
  page-footer: "Copyright 2026, Tomasz Szczerbicki"
  navbar:
    right:
      - text: O mnie 
        href: about.qmd
      - icon: envelope
        href: mailto:szczerbicki.tomasz@gmail.com
      - icon: github
        href: https://github.com/tszczerbicki
      - icon: twitter-x
        href: https://x.com/Shcherbytsky
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

lang: pl 

twitter-card: 
  card-style: summary
  site: "@Shcherbytsky"
  creator: "@Shcherbytsky"

